<?php
/**
 * @file
 * Code for the module.
 */

/**
 * Implements hook_preprocess_html().
 */
function lotame_adv_tags_preprocess_html(&$vars) {
  $client_id = lotame_get_client_id();

  if (!empty($client_id) && lotame_visibility_pages()) {
    // Load default tags. //@todo create UI with storage for this.
    $tags = module_invoke_all('lotame_adv_tags_default_tags');

    // Allow modules to alter the tags and add some extra logic if needed.
    drupal_alter('lotame_adv_tags_default_tags', $tags);

    if (empty($tags)) {
      return;
    }

    // Process tags.
    $tags = _lotame_adv_tags_process_tags($tags);
    $tags = _lotame_adv_tags_render_tokens($tags);
    $tags = array_unique($tags);
    sort($tags);

    $options = array(
      'every_page' => TRUE,
      'scope' => 'footer',
      'type' => 'inline',
      'weight' => 10,
    );

    drupal_add_js(implode("\n", $tags), $options);
  }
}

/**
 * Renders tags.
 *
 * @param $tags The Lotame adv tags tags.
 *
 * @return array Lotame adv tags.
 */
function _lotame_adv_tags_process_tags($tags) {
  $client_id = lotame_get_client_id();
  $processed_tags = array();
  $multi_value_tags = array();
  foreach ($tags as $tag) {
    // Check if there is any multi-value field.
    if ($multi_value_tokens = _lotame_adv_tags_tag_has_multi_value_tokens($tag)) {
      $keys = array_keys($multi_value_tokens);
      $token = reset($keys);
      foreach ($multi_value_tokens[$token] as $value) {
        $multi_value_tags[] = str_replace($token, trim($value), $tag);
      }
      // Multi-value fields will be processed after.
      continue;
    }

    $behaviour_type = 'ctax'; //@todo get this setting from the tag config.
    $js_tag = "_cc" . $client_id . ".add('" . $behaviour_type . "', '" . $tag . "');";

    array_push($processed_tags, $js_tag);
  }

  // Process multi-value fields.
  if (!empty($multi_value_tags)) {
    $multi_value_tags = _lotame_adv_tags_process_tags($multi_value_tags);
    $processed_tags = array_merge($processed_tags, $multi_value_tags);
  }

  return array_unique($processed_tags);
}

/**
 * Render tokens and clean entries with invalid tokens.
 *
 * @param $tags Tags.
 *
 * @return array Tags.
 */
function _lotame_adv_tags_render_tokens($tags) {
  foreach ($tags as $key => &$tag) {
    // Token replace for global tokens.
    $tag = token_replace($tag, lotame_get_token_data(), ['clear' => FALSE, 'sanitize' => FALSE]);

    // If any token did not get rendered, remove the tag.
    if (_lotame_adv_tags_get_tokens($tag)) {
      // Remove this tag.
      unset($tags[$key]);
    }
  }

  return $tags;
}

/**
 * Helper to get tokens that have multiple values.
 *
 * @param $str String
 *
 * @return array keyed array with tokens and the respective values.
 */
function _lotame_adv_tags_tag_has_multi_value_tokens($str) {
  $multi_value_tokens = array();
  $tokens = _lotame_adv_tags_get_multi_value_tokens($str);

  // Render tokens individually to find if any token has multiple values.
  foreach ($tokens as $token) {
    $value = token_replace($token, lotame_get_token_data());
    $values = explode(',', $value);

    if (is_array($values) && sizeof($values) > 1) {
      $multi_value_tokens[$token] = array_filter($values);
    }
  }

  if (!empty($multi_value_tokens)) {
    return $multi_value_tokens;
  }
}

/**
 * Helper to extract tokens from a string.
 *
 * @param $str The string.
 *
 * @return mixed The tokens, if found or NULL.
 */
function _lotame_adv_tags_get_tokens($str) {
  preg_match_all('/\[(.*?)\]/', $str, $matches);

  if (isset($matches[0]) && !empty($matches[0])) {
    return $matches;
  }
}

/**
 * Helper to find tokens that multiple values.
 *
 * @param $tag
 *
 * @return array List of tokens.
 */
function _lotame_adv_tags_get_multi_value_tokens($str) {
  $tokens = array();

  if ($matches = _lotame_adv_tags_get_tokens($str)) {
    foreach ($matches[0] as $token) {
      $tokens[] = $token;
    }
  }
  $tokens = array_unique($tokens);

  return $tokens;
}
